const LOGIN ='api/users/loginUser';
const SINGED_IN ='api/users/signUser';
const WORKER_LOGIN = 'api/worker/loginWorker';
const WORKER_REGISTER = 'api/worker/signWorker';
const GET_USER_DATA = 'api/users/5555/';
const Get_Worker_Data = 'api/worker/5555/getWorker';
const Get_Worker_Electronic= 'api/worker/getSpecialized/electronic';
const Get_Worker_Motor = 'api/worker/getSpecialized/motor';
const Get_Worker_Another = 'api/worker/getSpecialized/another';